---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: director-sa
  namespace: open-match
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agones-allocator-access
rules:
- apiGroups: ["allocation.agones.dev"]
  resources: ["gameserverallocations"]
  verbs: ["create"]
- apiGroups: ["agones.dev"]
  resources: ["gameservers", "gameserversets", "fleets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: director-agones-allocator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agones-allocator-access
subjects:
- kind: ServiceAccount
  name: director-sa
  namespace: open-match
